### PR TITLE
Update MAX31855.cpp

### PR DESCRIPTION
**Pull request by FabioBrondo**
Add RawData to get raw from the board and check no board status.
Refer to Issue #1

### CODE REVIEW

**Comment by RobTillaart** [comment]
I see no relevant changes under files changed, please check if you committed all the changes.

e.g. .h file should have the function prototype + the new variable **raw**

**Comment by FabioBrondo** [comment]
@RobTillaart sorry but i'm newbie on programming.
I'm trying to refresh mi C knowledge but i'm totally new on libraries editing...
I don't know where to start at the moment :(

**Comment by RobTillaart** [comment]
@Banfotech 
No problem, check out this free course material - https://guides.github.com/introduction/git-handbook/

**Comment by FabioBrondo** [comment]
> No problem, check out this free course material - https://guides.github.com/introduction/git-handbook/

Thanks @RobTillaart, i've got a look to the link you have sent to me, that is really usefull!

But  my ptoblem is coding, i have very little experience on it.
I don't know how to modify the file, that's why i've proposed that improvements to you, that are a lot more skilled than me!

**Comment by RobTillaart** [comment]
Then it will take a few days until I have some time.

**Pull request closed without merging**
